Move comments in function bodys for better Vim folds and optimize

diff --git a/files/secret/pki/lib/pki-authority b/files/secret/pki/lib/pki-authority
--- a/files/secret/pki/lib/pki-authority
+++ b/files/secret/pki/lib/pki-authority
@@ -4,15 +4,15 @@
 # Copyright (C) 2016 Maciej Delmanowski <drybjed@gmail.com>
 # Homepage: https://debops.org/
 
-set -eu -o pipefail
+set -o nounset -o pipefail -o errexit
 
 umask 022
 
 script="$(basename "${0}")"
 
-# OpenSSL writes to stderr/stdout even when there are no errors. So just
-# display the output if the exit code was != 0 to simplify debugging.
 _openssl () {
+    # OpenSSL writes to stderr/stdout even when there are no errors. So just
+    # display the output if the exit code was != 0 to simplify debugging.
     set +e
     _openssl_out="$(openssl ${@} 2>&1)"
     local rc=$?
@@ -23,23 +23,23 @@ _openssl () {
         echo "Details:" >&2
         echo "${_openssl_out}" >&2
         exit ${rc}
-  fi
-  unset _openssl_out
-  return ${rc}
+    fi
+    unset _openssl_out
+    return ${rc}
 }
 
-# Normalize version numbers for comparsion
 version () {
+    # Normalize version numbers for compassion.
     echo "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'
 }
 
-# Check if an associative array has a specified key present
 key_exists () {
+    # Check if an associative array has a specified key present
     eval '[ ${'$1'[$2]+test_of_existence} ]'
 }
 
-# Check if an element is in an array
 array_exists () {
+    # Check if an element is in an array
     local array="$1[@]"
     local seeking=${2}
     local in=1
@@ -52,23 +52,24 @@ array_exists () {
     return $in
 }
 
-# Get an absolute path to a file
 get_absolute_path () {
+    # Get an absolute path to a file
     python -c 'import sys, os.path; print(os.path.abspath(sys.argv[1]))' "${1}"
 }
 
-# Get a relative path to a file
 get_relative_path () {
+    # Get a relative path to a file
     python -c 'import sys, os.path; print(os.path.relpath(sys.argv[1], sys.argv[2]))' "${1}" "${2:-$PWD}"
 }
 
-# Wrap dnsdomainname if it's not present (on MacOS X)
 get_dnsdomainname () {
+    # Wrap dnsdomainname if it's not present (on MacOS X)
+
     if type dnsdomainname > /dev/null 2>&1 ; then
         dnsdomainname
     else
-
-        local fqdn="$(hostname -f)"
+        local fqdn
+        fqdn="$(hostname -f)"
         if [[ ${fqdn} == *.* ]] ; then
             echo "${fqdn#*.}"
         else
@@ -120,13 +121,6 @@ initialize_environment () {
     config["private_file_mode"]="600"
 
     test -d ${config['pki_root']} || mkdir -p -m ${config['public_dir_mode']} ${config['pki_root']}
-}
-
-print_usage () {
-    cat << EOF
-Usage: ${script} <command> [parameters]
-EOF
-
 }
 
 enter_authority () {
@@ -987,8 +981,8 @@ generate_openssl_serial () {
     fi
 }
 
-# GnuTLS doesn't use this, so do nothing
 generate_gnutls_serial () {
+    # GnuTLS doesn't use this, so do nothing
     return 0
 }
 
@@ -1492,7 +1486,12 @@ sub_init () {
     fi
 }
 
-subcommand=""
+print_usage () {
+    cat << EOF
+Usage: ${script} <command> [parameters]
+EOF
+
+}
 
 initialize_environment
 
@@ -1519,4 +1518,3 @@ else
     print_usage
     exit 1
 fi
-
