Implement per-realm locking using pidfiles

diff --git a/files/usr/local/lib/pki/pki-realm b/files/usr/local/lib/pki/pki-realm
--- a/files/usr/local/lib/pki/pki-realm
+++ b/files/usr/local/lib/pki/pki-realm
@@ -8,9 +8,64 @@ set -eu -o pipefail
 
 umask 022
 
-script="$(basename ${0})"
+script="${0}"
+script_name="$(basename ${script})"
+pid="$$"
 
 state=()
+
+# Display a message if script is used interactively, otherwise send it to syslog
+log_message () {
+    local msg="${1:-}"
+
+    if [ -n "${msg}" ] ; then
+        if tty -s > /dev/null 2>&1 ; then
+            echo "${script_name}: ${msg}" 1>&2
+        elif type logger > /dev/null 2>&1 ; then
+            logger -t "${script_name}[${pid}]" "${msg}"
+        fi
+    fi
+}
+
+# Clean up pidfile
+clean_up () {
+    local pidfile="${1}"
+
+    if [ -n "${pidfile}" -a -r ${pidfile} ] ; then
+        rm -f ${pidfile}
+    fi
+    exit 0
+}
+
+# Wait for the specified process to exit
+wait_for_pid () {
+    local pidfile="${1}"
+
+    if [ -n "${pidfile}" -a -r ${pidfile} ] ; then
+        while $(kill -0 $(<${pidfile}) > /dev/null 2>&1) ; do
+            log_message "Waiting for PID $(<${pidfile}) to finish"
+            sleep $[ ( $RANDOM % 5 ) + 1]m
+        done
+        test -f ${pidfile} && rm -f ${pidfile}
+    fi
+}
+
+create_lock () {
+    local pidfile="${1}"
+
+    # Try and lock the script operation
+    echo ${pid} > ${pidfile}
+    sleep 0.5
+
+    # Exclusive lock failed
+    if [ "x$(cat ${pidfile})" != "x"${pid} ] ; then
+        log_message "PKI management started by PID $(<${pidfile})"
+        exit 0
+    fi
+
+    # Exclusive lock succeded
+    trap "clean_up ${pidfile}" EXIT
+}
 
 # Check if an associative array has a specified key present
 key_exists() {
@@ -91,6 +146,8 @@ initialize_environment () {
 
     if [ "$EUID" -eq 0 ] ; then
 
+        config["lock_dir"]="/run"
+
         config["pki_root"]="${PKI_ROOT:-/etc/pki}"
         config["pki_library"]="${PKI_LIBRARY:-openssl}"
         config["pki_acme"]="${PKI_ACME:-true}"
@@ -134,6 +191,8 @@ initialize_environment () {
 
     else
 
+        config["lock_dir"]="${XDG_RUNTIME_DIR:-/tmp}"
+
         config["pki_root"]="${PKI_ROOT:-${XDG_CONFIG_HOME:-${HOME}/.config}/pki}"
         config["pki_library"]="${PKI_LIBRARY:-openssl}"
         config["pki_acme"]="${PKI_ACME:-true}"
@@ -172,7 +231,7 @@ initialize_environment () {
 
 print_usage () {
     cat << EOF
-Usage: ${script} <command> [parameters]
+Usage: ${script_name} <command> [parameters]
 EOF
 
 }
@@ -1215,7 +1274,7 @@ sub_new-realm () {
                 esac
                 ;;
             h)
-                echo "usage: ${script} new-realm <-n|--name[=]realm>" >&2
+                echo "usage: ${script_name} new-realm <-n|--name[=]realm>" >&2
                 exit 2
                 ;;
             n)
@@ -1230,6 +1289,11 @@ sub_new-realm () {
     done
 
     if key_exists args "name" ; then
+
+        local pidfile="${config['lock_dir']}/${script_name}-${args['name']}.pid"
+
+        wait_for_pid "${pidfile}"
+        create_lock "${pidfile}"
 
         enter_realm ${args['name']}
 
@@ -1438,7 +1502,7 @@ sub_init () {
                 esac
                 ;;
             h)
-                echo "usage: ${script} init <-n|--name[=]realm>" >&2
+                echo "usage: ${script_name} init <-n|--name[=]realm>" >&2
                 exit 2
                 ;;
             n)
@@ -1453,6 +1517,11 @@ sub_init () {
     done
 
     if key_exists args "name" ; then
+
+        local pidfile="${config['lock_dir']}/${script_name}-${args['name']}.pid"
+
+        wait_for_pid "${pidfile}"
+        create_lock "${pidfile}"
 
         enter_realm ${args['name']}
 
@@ -1508,7 +1577,7 @@ sub_run () {
                 esac
                 ;;
             h)
-                echo "usage: ${script} init <-n|--name[=]realm>" >&2
+                echo "usage: ${script_name} run <-n|--name[=]realm>" >&2
                 exit 2
                 ;;
             n)
@@ -1523,6 +1592,11 @@ sub_run () {
     done
 
     if key_exists args "name" ; then
+
+        local pidfile="${config['lock_dir']}/${script_name}-${args['name']}.pid"
+
+        wait_for_pid "${pidfile}"
+        create_lock "${pidfile}"
 
         enter_realm ${args['name']}
 
@@ -1555,7 +1629,7 @@ if [ $# -gt 0 ] ; then
                 ;;
 
             *)
-                echo "${script}: Error: unknown subcommand '${subcommand}'" >&2
+                echo "${script_name}: Error: unknown subcommand '${subcommand}'" >&2
                 print_usage
                 exit 1
                 ;;
