Various updates in 'renspahost-scheduler' script
Scheduler PID files are now stored in separate
'/run/rsnapshot-scheduler/' subdirectory. Scheduler stores the PID of
its process for each backup job before scheduling it using 'batch' or
'sleep', therefore repeated execution of the scheduler script won't
result in multiple backup jobs of the same type.

Scheduler logs are now more verbose, you can see each operation as it
happens.

Because 'batch' processes submitted jobs in order, scheduler now
randomizes list of hosts to make backup jobs less repetitive and
hopefully less resource intensive in the long run.

diff --git a/templates/usr/local/lib/rsnapshot-scheduler.j2 b/templates/usr/local/lib/rsnapshot-scheduler.j2
--- a/templates/usr/local/lib/rsnapshot-scheduler.j2
+++ b/templates/usr/local/lib/rsnapshot-scheduler.j2
@@ -22,11 +22,13 @@ EOF
 
 }
 
-script="$0"
+script="${0}"
 
 scheduler_config="/etc/$(basename ${script}).conf"
 
 scheduler_config_dir="/etc/rsnapshot"
+scheduler_hosts_dir="${scheduler_config_dir}"
+scheduler_lock_dir="/run/rsnapshot-scheduler"
 scheduler_type="batch"
 scheduler_sleep_max_delay="20"
 scheduler_run_max_delay="5"
@@ -35,9 +37,9 @@ scheduler_run_max_delay="5"
 
 pid="$$"
 
-mode="${1}"
-backup_level="${2}"
-host="${3}"
+arg_mode="${1}"
+arg_backup_level="${2}"
+arg_host="${3}"
 
 log_message () {
     if tty -s > /dev/null 2>&1 ; then
@@ -47,89 +49,133 @@ log_message () {
     fi
 }
 
-if [ -z "${mode}" ] ; then
+if [ -r ${scheduler_config_dir}/stop -o -r ${scheduler_config_dir}/disable -o -r ${scheduler_config_dir}/disabled ] ; then
+    log_message "Exit: rsnapshot backups are disabled globally"
+    exit 0
+fi
+
+if [ -z "${arg_mode}" ] ; then
     display_usage
     exit 0
 fi
 
-if [ -z "${backup_level}" ] ; then
+if [ -z "${arg_backup_level}" ] ; then
     log_message "Error: backup level not specified"
     exit 1
 fi
 
-if [ -z "${host}" ] ; then
+if [ -z "${arg_host}" ] ; then
     log_message "Error: host not specified"
     exit 1
 fi
 
-scheduler_pidfile="/run/$(basename ${script})-${backup_level}-${host}.pid"
-
 clean_up () {
+
+    local backup_level="${1}"
+    local host="${2}"
+
+    local scheduler_pidfile="${scheduler_lock_dir}/$(basename ${script})-${backup_level}-${host}.pid"
+
     test -f ${scheduler_pidfile} && rm -f ${scheduler_pidfile}
 }
 
-if [ -r ${scheduler_config_dir}/${host}/stop -o -r ${scheduler_config_dir}/${host}/disable -o -r ${scheduler_config_dir}/${host}/disabled ] ; then
-    log_message "Exit: backup of ${host} is disabled"
-    exit 0
-fi
+wait_for_pid () {
 
-if [ "${host}" != "all" ] ; then
-    if [ -d ${scheduler_config_dir}/${host} ] ; then
-        config="${scheduler_config_dir}/${host}/rsnapshot.conf"
-    else
-        log_message "Error: configuration for ${host} not found"
-        exit 1
+    local backup_level="${1}"
+    local host="${2}"
+
+    local scheduler_pidfile="${scheduler_lock_dir}/$(basename ${script})-${backup_level}-${host}.pid"
+
+    if [ -f ${scheduler_pidfile} ] ; then
+        while $(kill -0 $(<${scheduler_pidfile}) > /dev/null 2>&1) ; do
+            log_message "Scheduled ${backup_level} backup of host ${host} is waiting for PID $(<${scheduler_pidfile}) to finish"
+            sleep $[ ( $RANDOM % ${scheduler_run_max_delay} ) + 1]m
+        done
+        test -f ${scheduler_pidfile} && rm -f ${scheduler_pidfile}
     fi
-fi
+
+}
 
 delay_backup () {
-    sleep $[ ( $RANDOM % ${scheduler_sleep_max_delay} ) + 1 ]m
+
+    local delay="${1}"
+
+    if [ -n "${delay}" ] ; then
+        sleep ${delay}
+    else
+        sleep $[ ( $RANDOM % ${scheduler_sleep_max_delay} ) + 1 ]m
+    fi
 }
 
 run_backup () {
+
+    local backup_level="${1}"
+    local host="${2}"
+
+    local scheduler_pidfile="${scheduler_lock_dir}/$(basename ${script})-${backup_level}-${host}.pid"
 
     if [ "${host}" == "all" ] ; then
         log_message "Error: cannot backup host ${host}"
         exit 1
     fi
 
+    if [ -r ${scheduler_hosts_dir}/${host}/rsnapshot.conf ] ; then
+        local config="${scheduler_hosts_dir}/${host}/rsnapshot.conf"
+    else
+        log_message "Error: configuration for ${host} not found"
+        exit 1
+    fi
+
+    if [ -r ${scheduler_hosts_dir}/${host}/stop -o -r ${scheduler_hosts_dir}/${host}/disable -o -r ${scheduler_hosts_dir}/${host}/disabled ] ; then
+        log_message "Exit: backup of ${host} is disabled"
+        exit 0
+    fi
+
     if [ -r ${config} ] ; then
-
-        if [ -f ${scheduler_pidfile} ] ; then
-            if $(kill -0 $(<${scheduler_pidfile}) > /dev/null 2>&1) ; then
-                log_message "Exit: Backup of ${host} at ${backup_level} level already in progress, managed by PID $(cat ${scheduler_pidfile})"
-                exit 0
-            else
-                rm -f ${scheduler_pidfile}
-            fi
-        fi
-
-        echo ${pid} > ${scheduler_pidfile}
-        sleep 1
-
-        if [ "x$(cat ${scheduler_pidfile})" != "x"${pid} ] ; then
-            log_message "Exit: Backup of ${host} at ${backup_level} level started by PID $(cat ${scheduler_pidfile}), exiting"
-            exit 0
-        fi
-
-        trap clean_up EXIT
 
         sync_first=( $(grep -E "^sync_first\s+1" ${config}) )
         retain_first=( $(grep -E "^retain\s+" ${config} | awk '{print $2}' | head -n 1) )
         retain_name=( $(grep -E "^retain\s+${backup_level}\s+" ${config} | awk '{print $2}' | head -n 1) )
         lockfile=( $(grep -E "^lockfile\s+" ${config} | awk '{print $2}' | head -n 1) )
 
-        if [ -n "${lockfile}" ] && [ -r ${lockfile} ] ; then
-            if $(kill -0 $(<${lockfile}) > /dev/null 2>&1) ; then
-                while [ -r ${lockfile} ] ; do
-                    sleep $[ ( $RANDOM % ${scheduler_run_max_delay} ) + 1]m
-                done
-            fi
-        fi
-
         if [ "${retain_name}" == "${backup_level}" ] ; then
+
+            if [ -f ${scheduler_pidfile} ] ; then
+                if $(kill -0 $(<${scheduler_pidfile}) > /dev/null 2>&1) ; then
+                    log_message "Exit: Backup of ${host} at ${backup_level} level already in progress, managed by PID $(cat ${scheduler_pidfile})"
+                    exit 0
+                else
+                    rm -f ${scheduler_pidfile}
+                fi
+            fi
+
+            test -d $(dirname ${scheduler_pidfile}) || mkdir -p -m 755 $(dirname ${scheduler_pidfile})
+            echo ${pid} > ${scheduler_pidfile}
+            sleep 1
+
+            if [ "x$(cat ${scheduler_pidfile})" != "x"${pid} ] ; then
+                log_message "Exit: Backup of ${host} at ${backup_level} level started by PID $(cat ${scheduler_pidfile}), exiting"
+                exit 0
+            fi
+
+            trap "clean_up ${backup_level} ${host}" EXIT
+
+            if [ -n "${lockfile}" ] && [ -r ${lockfile} ] ; then
+                if $(kill -0 $(<${lockfile}) > /dev/null 2>&1) ; then
+                    while [ -r ${lockfile} ] ; do
+                        sleep $[ ( $RANDOM % ${scheduler_run_max_delay} ) + 1]m
+                    done
+                fi
+            fi
+
             if [ -n "${sync_first}" ] && [ "${retain_name}" == "${retain_first}" ] ; then
+                log_message "Starting sync for ${backup_level} backup of ${host}"
                 rsnapshot -c ${config} sync
+            fi
+            if [ -n "${sync_first}" ] && [ "${retain_name}" == "${retain_first}" ] ; then
+                log_message "Rotating ${backup_level} snapshot of ${host}"
+            else
+                log_message "Starting ${backup_level} backup of ${host}"
             fi
             rsnapshot -c ${config} ${backup_level}
         else
@@ -150,31 +196,56 @@ prepare_backup () {
     local backup_level="${1}"
     local host="${2}"
 
-    if [ -d ${scheduler_config_dir}/${host} ] ; then
-        local config="${scheduler_config_dir}/${host}/rsnapshot.conf"
+    local scheduler_pidfile="${scheduler_lock_dir}/$(basename ${script})-${backup_level}-${host}.pid"
+
+    if [ -r ${scheduler_hosts_dir}/${host}/rsnapshot.conf ] ; then
+        local config="${scheduler_hosts_dir}/${host}/rsnapshot.conf"
     else
         log_message "Error: configuration for ${host} not found"
-        exit 1
+        return
     fi
 
-    retain_name=( $(grep -E "^retain\s+${backup_level}\s+" ${config} | awk '{print $2}' | head -n 1) )
+    if [ -r ${scheduler_hosts_dir}/${host}/stop -o -r ${scheduler_hosts_dir}/${host}/disable -o -r ${scheduler_hosts_dir}/${host}/disabled ] ; then
+        log_message "Exit: backup of ${host} is disabled"
+        return
+    fi
 
-    if [ "${retain_name}" == "${backup_level}" ] ; then
+    if [ -r ${config} ] ; then
 
-        if [ "${scheduler_type}" == "batch" ] ; then
+        local retain_name=( $(grep -E "^retain\s+${backup_level}\s+" ${config} | awk '{print $2}' | head -n 1) )
 
-            if type batch > /dev/null 2>&1 ; then
-                log_message "Scheduling ${backup_level} backup of ${host} using batch"
-                echo "${script} run ${backup_level} ${host}" | batch > /dev/null 2>&1
-            else
-                log_message "Scheduling ${backup_level} backup of ${host}"
-                (${script} delayrun ${backup_level} ${host}) &
+        if [ "${retain_name}" == "${backup_level}" ] ; then
+
+            if [ -f ${scheduler_pidfile} ] ; then
+                log_message "Backup of ${host} at ${backup_level} level already in progress, managed by PID $(cat ${scheduler_pidfile})"
+                return
             fi
 
-        elif [ "${scheduler_type}" == "sleep" ] ; then
+            test -d $(dirname ${scheduler_pidfile}) || mkdir -p -m 755 $(dirname ${scheduler_pidfile})
+            echo ${pid} > ${scheduler_pidfile}
+            sleep 1
 
-            log_message "Scheduling ${backup_level} backup of ${host}"
-            (${script} delayrun ${backup_level} ${host}) &
+            if [ "x$(cat ${scheduler_pidfile})" != "x"${pid} ] ; then
+                log_message "Backup of ${host} at ${backup_level} level started by PID $(cat ${scheduler_pidfile})"
+                return
+            fi
+
+            if [ "${scheduler_type}" == "batch" ] ; then
+
+                if type batch > /dev/null 2>&1 ; then
+                    log_message "Scheduling ${backup_level} backup of ${host} using batch"
+                    echo "${script} batchrun ${backup_level} ${host}" | batch > /dev/null 2>&1
+                else
+                    log_message "Scheduling ${backup_level} backup of ${host}"
+                    (${script} delayrun ${backup_level} ${host}) &
+                fi
+
+            elif [ "${scheduler_type}" == "sleep" ] ; then
+
+                log_message "Scheduling ${backup_level} backup of ${host}"
+                (${script} delayrun ${backup_level} ${host}) &
+
+            fi
 
         fi
 
@@ -183,22 +254,27 @@ prepare_backup () {
 
 schedule_backup () {
 
+    local backup_level="${1}"
+    local host="${2}"
+
     if [ "${host}" != "all" ] ; then
 
         prepare_backup ${backup_level} ${host}
 
     elif [ "${host}" == "all" ] ; then
-        for name in ${scheduler_config_dir}/* ; do
+        local random_hosts=( $(ls -1 --indicator-style=none ${scheduler_hosts_dir} | sort -R | xargs) )
+        for name in ${random_hosts[@]} ; do
             prepare_backup ${backup_level} $(basename ${name})
         done
     fi
 
 }
 
-case ${mode} in
-    run)         run_backup ;;
-    delayrun)    delay_backup ; run_backup ;;
-    schedule)    schedule_backup ;;
+case ${arg_mode} in
+    run)         run_backup ${arg_backup_level} ${arg_host} ;;
+    batchrun)    wait_for_pid ${arg_backup_level} ${arg_host} ; run_backup ${arg_backup_level} ${arg_host} ;;
+    delayrun)    delay_backup ; run_backup ${arg_backup_level} ${arg_host} ;;
+    schedule)    schedule_backup ${arg_backup_level} ${arg_host} ;;
     *)           display_usage && exit 0 ;;
 esac
 
