Add custom container options, POSIX capabilities
- when a container is created, template script will look for a special
  file in '/tmp', and if found, its contents will be appended to the
  container configuration file;

- you can now define which POSIX capabilities should be dropped in a LXC
  container at the start. These can be system-wide
  (lxc_capabilities_drop), per template (currently only
  lxc_template_capabilities_drop), and per container
  (item.capabilities_drop). All lists are configured separately and their
  effects are cumulative;

diff --git a/templates/usr/share/lxc/templates/lxc-debops.j2 b/templates/usr/share/lxc/templates/lxc-debops.j2
--- a/templates/usr/share/lxc/templates/lxc-debops.j2
+++ b/templates/usr/share/lxc/templates/lxc-debops.j2
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# This file is managed by Ansible, all changes will be lost
+# {{ ansible_managed }}
 
 # lxc: linux Container library
 
@@ -104,6 +104,50 @@ EOF
 
     # Unlock service startup
     rm -rf $rootfs/usr/sbin/policy-rc.d
+
+    return 0
+}
+
+debops_configuration()
+{
+    path=$1
+    rootfs=$2
+    hostname=$3
+    arch=$4
+
+{% if lxc_capabilities_drop is defined and lxc_capabilities_drop %}
+    ## Drop these POSIX capabilities in all containers
+    echo "" >> $path/config
+    echo "# Drop these POSIX capabilities in all containers" >> $path/config
+    echo "lxc.cap.drop = {{ lxc_capabilities_drop | join(' ') }}" >> $path/config
+{% endif %}
+{% if lxc_template_capabilities_drop is defined and lxc_template_capabilities_drop %}
+    ## Drop these POSIX capabilities in containers
+    ## created by this template
+    echo "" >> $path/config
+    echo "# Drop these POSIX capabilities in containers created by $(basename $0)" >> $path/config
+    echo "lxc.cap.drop = {{ lxc_template_capabilities_drop | join(' ') }}" >> $path/config
+{% endif %}
+{% if lxc_template_config_options is defined and lxc_template_config_options %}
+
+    ## Additional template options
+    echo "" >> $path/config
+    echo "# Custom template options" >> $path/config
+
+    cat <<EOF >> $path/config
+{{ lxc_template_config_options }}
+EOF
+
+{% endif %}
+    if [ -r /tmp/lxc_temp_${hostname}_append.conf ] ; then
+        echo "" >> $path/config
+        echo "# Custom container options" >> $path/config
+        cat /tmp/lxc_temp_${hostname}_append.conf >> $path/config
+    fi
+    if [ $? -ne 0 ]; then
+        echo "Failed to add configuration"
+        return 1
+    fi
 
     return 0
 }
@@ -517,6 +561,12 @@ if [ $? -ne 0 ]; then
 fi
 
 copy_configuration $path $rootfs $name $arch
+if [ $? -ne 0 ]; then
+    echo "failed write configuration file"
+    exit 1
+fi
+
+debops_configuration $path $rootfs $name $arch
 if [ $? -ne 0 ]; then
     echo "failed write configuration file"
     exit 1
