[mazer] The 'ansible/galaxy.yml' file was removed
Check the execution location against the expected location of the
'make-collection' script itself.

(cherry picked from commit 4bfb5f088d1fc2565121a130e84314853316f3ad)

diff --git a/lib/mazer/make-collection b/lib/mazer/make-collection
--- a/lib/mazer/make-collection
+++ b/lib/mazer/make-collection
@@ -10,8 +10,8 @@
 set -o nounset -o pipefail -o errexit
 
 # Check if we are in the correct directory
-if ! [ -f ansible/galaxy.yml ] ; then
-    printf "%s\n" "Error: this script needs to be executed in the root of the DebOps repository"
+if ! [ -f lib/mazer/make-collection ] ; then
+    printf "%s\\n" "Error: this script needs to be executed in the root of the DebOps repository"
     exit 1
 fi
 
