Rewrite of 'lxc' role
- 'lxc' role has been rewritten to support LXC 1.0 on Debian Wheezy;
- lxc 1.0 .deb packages will be automatically built if needed, they can
  be automatically shared with other hosts using local APT repository;
- 'lxc' role can manage LXC containers using simple YAML list;

diff --git a/playbooks/roles/ginas.lxc/templates/usr/share/lxc/templates/lxc-ginas.j2 b/playbooks/roles/ginas.lxc/templates/usr/share/lxc/templates/lxc-ginas.j2
--- a/playbooks/roles/ginas.lxc/templates/usr/share/lxc/templates/lxc-ginas.j2
+++ b/playbooks/roles/ginas.lxc/templates/usr/share/lxc/templates/lxc-ginas.j2
@@ -20,24 +20,62 @@
 
 # You should have received a copy of the GNU Lesser General Public
 # License along with this library; if not, write to the Free Software
-# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
+# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 
-# ==============================================================
-# This is a slightly modified version by Rob van der Hoeven
-# I use it for my FreedomBox project: http://freedomboxblog.nl
-# ==============================================================
+# Detect use under userns (unsupported)
+for arg in "$@"; do
+    [ "$arg" = "--" ] && break
+    if [ "$arg" = "--mapped-uid" -o "$arg" = "--mapped-gid" ]; then
+        echo "This template can't be used for unprivileged containers." 1>&2
+        echo "You may want to try the \"download\" template instead." 1>&2
+        exit 1
+    fi
+done
+
+# Make sure the usual locations are in PATH
+export PATH=$PATH:/usr/sbin:/usr/bin:/sbin:/bin
+
+MIRROR=${MIRROR:-{{ lxc_template_debootstrap_mirror }}}
+LOCALSTATEDIR="/var"
+LXC_TEMPLATE_CONFIG="/usr/share/lxc/config"
+
+bootstrap_ginas()
+{
+    rootfs=$1
+    hostname=$2
+
+    # Configure SSH public key from Ansible Controller for root account
+    mkdir -m 700 $rootfs/root/.ssh
+    echo "{{ lxc_template_root_authorized_key }}" > $rootfs/root/.ssh/authorized_keys
+
+    # Configure admin account
+    chroot $rootfs addgroup --system admins
+    echo "%admins ALL = (ALL) NOPASSWD: ALL" > $rootfs/etc/sudoers.d/admins
+    chroot $rootfs chmod 440 /etc/sudoers.d/admins
+    chroot $rootfs adduser --disabled-password --home /home/{{ lxc_template_admin_account }} --gecos "System Administrator" {{ lxc_template_admin_account }}
+    chroot $rootfs adduser {{ lxc_template_admin_account }} admins
+    chroot $rootfs mkdir -m 700 /home/{{ lxc_template_admin_account }}/.ssh
+    echo "{{ lxc_template_admin_authorized_key }}" > $rootfs/home/{{ lxc_template_admin_account }}/.ssh/authorized_keys
+    chroot $rootfs chown -R {{ lxc_template_admin_account }}:{{ lxc_template_admin_account }} /home/{{ lxc_template_admin_account }}/.ssh
+
+    # Set root password in a container
+    echo "root:{{ lxc_template_root_password }}" | chroot $rootfs chpasswd
+    echo "Container root password is '{{ lxc_template_root_password }}'"
+
+    return 0
+}
 
 configure_debian()
 {
     rootfs=$1
     hostname=$2
 
-    # Wheezy only has /dev/tty and /dev/tty0 by default,
+    # squeeze only has /dev/tty and /dev/tty0 by default,
     # therefore creating missing device nodes for tty1-4.
     for tty in $(seq 1 4); do
-    if [ ! -e $rootfs/dev/tty$tty ]; then
-       mknod $rootfs/dev/tty$tty c 4 $tty
-    fi
+        if [ ! -e $rootfs/dev/tty$tty ]; then
+            mknod $rootfs/dev/tty$tty c 4 $tty
+        fi
     done
 
     # configure the inittab
@@ -58,28 +96,19 @@ c1:12345:respawn:/sbin/getty 38400 tty1 linux
 c2:12345:respawn:/sbin/getty 38400 tty2 linux
 c3:12345:respawn:/sbin/getty 38400 tty3 linux
 c4:12345:respawn:/sbin/getty 38400 tty4 linux
+p6::ctrlaltdel:/sbin/init 6
+p0::powerfail:/sbin/init 0
 EOF
 
-    # configure fstab
-    cat <<EOF > $rootfs/etc/fstab
-# UNCONFIGURED FSTAB FOR BASE SYSTEM
-EOF
-
-    # configure /etc/hosts
-    cat <<EOF > $rootfs/etc/hosts
-127.0.0.1	localhost
-::1		localhost ip6-localhost ip6-loopback
-fe00::0		ip6-localnet
-ff00::0		ip6-mcastprefix
-ff02::1		ip6-allnodes
-ff02::2		ip6-allrouters
-EOF
+    # symlink mtab
+    [ -e "$rootfs/etc/mtab" ] && rm $rootfs/etc/mtab
+    ln -s /proc/self/mounts $rootfs/etc/mtab
 
     # disable selinux in debian
     mkdir -p $rootfs/selinux
     echo 0 > $rootfs/selinux/enforce
 
-    # configure the network using dhcp
+    # configure the network using the dhcp
     cat <<EOF > $rootfs/etc/network/interfaces
 auto lo
 iface lo inet loopback
@@ -93,95 +122,153 @@ EOF
 $hostname
 EOF
 
-    # let dhcp client report the hostname to dnsmasq
-    cat <<EOF >> $rootfs/etc/dhcp/dhclient.conf
-send host-name "$hostname";
-send vendor-class-identifier "lxc.module";
-EOF
-
     # reconfigure some services
     if [ -z "$LANG" ]; then
-	chroot $rootfs locale-gen {{ lxc_locale }}
-	chroot $rootfs update-locale LANG={{ lxc_locale }}
+        chroot $rootfs locale-gen en_US.UTF-8 UTF-8
+        chroot $rootfs update-locale LANG=en_US.UTF-8
     else
-	chroot $rootfs locale-gen $LANG
-	chroot $rootfs update-locale LANG=$LANG
+        encoding=$(echo $LANG | cut -d. -f2)
+        chroot $rootfs sed -e "s/^# \(${LANG} ${encoding}\)/\1/" \
+            -i /etc/locale.gen 2>/dev/null
+        chroot $rootfs locale-gen $LANG $encoding
+        chroot $rootfs update-locale LANG=$LANG
     fi
 
     # remove pointless services in a container
+    chroot $rootfs /usr/sbin/update-rc.d -f checkroot.sh remove
     chroot $rootfs /usr/sbin/update-rc.d -f umountfs remove
     chroot $rootfs /usr/sbin/update-rc.d -f hwclock.sh remove
     chroot $rootfs /usr/sbin/update-rc.d -f hwclockfirst.sh remove
 
-    echo "root:{{ lxc_rootpw }}" | chroot $rootfs chpasswd
-    echo "Root password is '{{ lxc_rootpw }}', please change !"
+    # generate new SSH keys
+    if [ -x $rootfs/var/lib/dpkg/info/openssh-server.postinst ]; then
+        cat > $rootfs/usr/sbin/policy-rc.d << EOF
+#!/bin/sh
+exit 101
+EOF
+        chmod +x $rootfs/usr/sbin/policy-rc.d
 
-    # Force password change, container is in public IP space
-    # FIXME: password shows up when logged in over ssh. Function disabled for now
-    #chroot $rootfs passwd --expire root
+        if [ -f $rootfs/etc/init/ssh.conf ]; then
+            mv $rootfs/etc/init/ssh.conf $rootfs/etc/init/ssh.conf.disabled
+        fi
+
+        rm -f $rootfs/etc/ssh/ssh_host_*key*
+
+        DPKG_MAINTSCRIPT_PACKAGE=openssh DPKG_MAINTSCRIPT_NAME=postinst chroot $rootfs /var/lib/dpkg/info/openssh-server.postinst configure
+        sed -i "s/root@$(hostname)/root@$hostname/g" $rootfs/etc/ssh/ssh_host_*.pub
+
+        if [ -f "$rootfs/etc/init/ssh.conf.disabled" ]; then
+            mv $rootfs/etc/init/ssh.conf.disabled $rootfs/etc/init/ssh.conf
+        fi
+
+        rm -f $rootfs/usr/sbin/policy-rc.d
+    fi
+
+    # set initial timezone as on host
+    if [ -f /etc/timezone ]; then
+        cat /etc/timezone > $rootfs/etc/timezone
+        chroot $rootfs dpkg-reconfigure -f noninteractive tzdata
+    elif [ -f /etc/sysconfig/clock ]; then
+        . /etc/sysconfig/clock
+        echo $ZONE > $rootfs/etc/timezone
+        chroot $rootfs dpkg-reconfigure -f noninteractive tzdata
+    else
+        echo "Timezone in container is not configured. Adjust it manually."
+    fi
+
+    echo "root:root" | chroot $rootfs chpasswd
+    echo "Root password is 'root', please change !"
 
     return 0
 }
 
+cleanup()
+{
+    rm -rf $cache/partial-$release-$arch
+    rm -rf $cache/rootfs-$release-$arch
+}
+
 download_debian()
 {
-    rootfs=$1
+    packages={{ lxc_template_debootstrap_packages | join(',') }}
+    cache=$1
     arch=$2
+    release=$3
 
-    echo "Downloading Debian Stable ..."
-    multistrap --shortcut stable --dir $rootfs --arch $arch
+    trap cleanup EXIT SIGHUP SIGINT SIGTERM
+    # check the mini debian was not already downloaded
+    mkdir -p "$cache/partial-$release-$arch"
     if [ $? -ne 0 ]; then
-	echo "Failed to download the rootfs, aborting."
-	return 1
+        echo "Failed to create '$cache/partial-$release-$arch' directory"
+        return 1
     fi
 
+    # download a mini debian into a cache
+    echo "Downloading debian minimal ..."
+    debootstrap --verbose --variant=minbase --arch=$arch \
+        --include=$packages \
+        "$release" "$cache/partial-$release-$arch" $MIRROR
+    if [ $? -ne 0 ]; then
+        echo "Failed to download the rootfs, aborting."
+        return 1
+    fi
+
+    mv "$1/partial-$release-$arch" "$1/rootfs-$release-$arch"
+    echo "Download complete."
+    trap EXIT
+    trap SIGINT
+    trap SIGTERM
+    trap SIGHUP
+
+    return 0
+}
+
+copy_debian()
+{
+    cache=$1
+    arch=$2
+    rootfs=$3
+    release=$4
+
+    # make a local copy of the minidebian
+    echo -n "Copying rootfs to $rootfs..."
+    mkdir -p $rootfs
+    rsync -Ha "$cache/rootfs-$release-$arch"/ $rootfs/ || return 1
     return 0
 }
 
 install_debian()
 {
+    cache="$LOCALSTATEDIR/cache/lxc/debian-ginas"
     rootfs=$1
-    mkdir -p /var/lock/subsys/
+    release=$2
+    arch=$3
+    mkdir -p $LOCALSTATEDIR/lock/subsys/
     (
-	flock -n -x 200
-	if [ $? -ne 0 ]; then
-	    echo "Cache repository is busy."
-	    return 1
-	fi
+        flock -x 9
+        if [ $? -ne 0 ]; then
+            echo "Cache repository is busy."
+            return 1
+        fi
 
-	arch=$(arch)
-	if [ "$arch" == "x86_64" ]; then
-	    arch=amd64
-	fi
+        echo "Checking cache download in $cache/rootfs-$release-$arch ... "
+        if [ ! -e "$cache/rootfs-$release-$arch" ]; then
+            download_debian $cache $arch $release
+            if [ $? -ne 0 ]; then
+                echo "Failed to download 'debian base'"
+                return 1
+            fi
+        fi
 
-	if [ "$arch" == "i686" ]; then
-	    arch=i386
-	fi
+        copy_debian $cache $arch $rootfs $release
+        if [ $? -ne 0 ]; then
+            echo "Failed to copy rootfs"
+            return 1
+        fi
 
-	if [ "$arch" == "armv5tel" ]; then
-	    arch=armel
-	fi
+        return 0
 
-	mkdir -p $rootfs/dev
-	chmod 755 $rootfs/dev
-	chown 0:0 $rootfs/dev
-        mknod $rootfs/dev/random c 1 8
-	chmod 666 $rootfs/dev/random
-	chown 0:0 $rootfs/dev/random
-	mknod $rootfs/dev/urandom c 1 9
-	chmod 666 $rootfs/dev/urandom
-	chown 0:0 $rootfs/dev/urandom
-	mknod $rootfs/dev/null c 1 3
-	chmod 666 $rootfs/dev/null
-        download_debian $rootfs $arch
-	cp -f /etc/locale.gen $rootfs/etc/locale.gen
-        DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true LC_ALL=C LANGUAGE=C LANG=C chroot $rootfs dpkg --configure -a
-	cp -f /etc/timezone $rootfs/etc/timezone
-	chroot $rootfs dpkg-reconfigure -f noninteractive tzdata
-
-	return 0
-
-	) 200>/var/lock/subsys/lxc
+        ) 9>$LOCALSTATEDIR/lock/subsys/lxc-debian
 
     return $?
 }
@@ -190,97 +277,152 @@ copy_configuration()
 {
     path=$1
     rootfs=$2
-    name=$3
+    hostname=$3
+    arch=$4
+
+    # Generate the configuration file
+    ## Create the fstab (empty by default)
+    touch $path/fstab
+
+    # if there is exactly one veth network entry, make sure it has an
+    # associated hwaddr.
+    nics=`grep -e '^lxc\.network\.type[ \t]*=[ \t]*veth' $path/config | wc -l`
+    if [ $nics -eq 1 ]; then
+        grep -q "^lxc.network.hwaddr" $path/config || sed -i -e "/^lxc\.network\.type[ \t]*=[ \t]*veth/a lxc.network.hwaddr = 00:16:3e:$(openssl rand -hex 3| sed 's/\(..\)/\1:/g; s/.$//')" $path/config
+    fi
+
+    ## Add all the includes
+    echo "" >> $path/config
+    echo "# Common configuration" >> $path/config
+    if [ -e "${LXC_TEMPLATE_CONFIG}/debian.common.conf" ]; then
+        echo "lxc.include = ${LXC_TEMPLATE_CONFIG}/debian.common.conf" >> $path/config
+    fi
+    if [ -e "${LXC_TEMPLATE_CONFIG}/debian.${release}.conf" ]; then
+        echo "lxc.include = ${LXC_TEMPLATE_CONFIG}/debian.${release}.conf" >> $path/config
+    fi
+
+    ## Add the container-specific config
+    echo "" >> $path/config
+    echo "# Container specific configuration" >> $path/config
+    grep -q "^lxc.rootfs" $path/config 2>/dev/null || echo "lxc.rootfs = $rootfs" >> $path/config
 
     cat <<EOF >> $path/config
-
-# Container
-lxc.utsname = $name
-lxc.rootfs = $rootfs
-lxc.tty = 4
-lxc.pts = 1024
-
-# Capabilities
-lxc.cap.drop	    = mac_admin
-lxc.cap.drop	    = mac_override
-lxc.cap.drop	    = sys_module
-lxc.cap.drop	    = sys_admin
-
-# Devices
-lxc.cgroup.devices.deny = a
-# /dev/null and zero
-lxc.cgroup.devices.allow = c 1:3 rwm
-lxc.cgroup.devices.allow = c 1:5 rwm
-# consoles
-lxc.cgroup.devices.allow = c 5:1 rwm
-lxc.cgroup.devices.allow = c 5:0 rwm
-lxc.cgroup.devices.allow = c 4:0 rwm
-lxc.cgroup.devices.allow = c 4:1 rwm
-# /dev/{,u}random
-lxc.cgroup.devices.allow = c 1:9 rwm
-lxc.cgroup.devices.allow = c 1:8 rwm
-lxc.cgroup.devices.allow = c 136:* rwm
-lxc.cgroup.devices.allow = c 5:2 rwm
-# rtc
-lxc.cgroup.devices.allow = c 254:0 rwm
-
-# Limits
-#lxc.cgroup.cpu.shares                  = 1024
-#lxc.cgroup.cpuset.cpus                 = 0
-#lxc.cgroup.memory.limit_in_bytes       = 256M
-#lxc.cgroup.memory.memsw.limit_in_bytes = 1G
-
-# Mount points
-lxc.mount.entry=proc $rootfs/proc proc ro,nodev,noexec,nosuid 0 0
-lxc.mount.entry=sysfs $rootfs/sys sysfs ro  0 0
-
-# Networking
-lxc.network.type = veth
-lxc.network.flags = up
-lxc.network.link = {{ lxc_external_interface }}
-lxc.network.ipv4 = 0.0.0.0/24
-lxc.network.hwaddr = 00:1E:$(hex):$(hex):$(hex):$(hex)
+lxc.mount = $path/fstab
+lxc.utsname = $hostname
+lxc.arch = $arch
 EOF
 
     if [ $? -ne 0 ]; then
-	echo "Failed to add configuration"
-	return 1
+        echo "Failed to add configuration"
+        return 1
     fi
 
     return 0
 }
 
-# nice trick from: http://mindref.blogspot.com/2011/01/debian-lxc-create.html
-hex()
+clean()
 {
-    echo "`tr -dc A-F0-9 < /dev/urandom | head -c 2 | xargs`"
+    cache="$LOCALSTATEDIR/cache/lxc/debian-ginas"
+
+    if [ ! -e $cache ]; then
+        exit 0
+    fi
+
+    # lock, so we won't purge while someone is creating a repository
+    (
+        flock -x 9
+        if [ $? != 0 ]; then
+            echo "Cache repository is busy."
+            exit 1
+        fi
+
+        echo -n "Purging the download cache..."
+        rm --preserve-root --one-file-system -rf $cache && echo "Done." || exit 1
+        exit 0
+
+    ) 9>$LOCALSTATEDIR/lock/subsys/lxc-debian
 }
 
 usage()
 {
     cat <<EOF
-$1 -h|--help -p|--path=<path>
+$1 -h|--help -p|--path=<path> [-a|--arch] [-r|--release=<release>] [-c|--clean]
+release: the debian release (e.g. wheezy): defaults to current stable
+arch: the container architecture (e.g. amd64): defaults to host arch
 EOF
     return 0
 }
 
-options=$(getopt -o hp:n:c -l help,path:,name: -- "$@")
+options=$(getopt -o hp:n:a:r:c -l help,rootfs:,path:,name:,arch:,release:,clean -- "$@")
 if [ $? -ne 0 ]; then
         usage $(basename $0)
-	exit 1
+        exit 1
 fi
 eval set -- "$options"
+
+if which dpkg >/dev/null 2>&1 ; then
+    arch=$(dpkg --print-architecture)
+else
+    arch=$(uname -m)
+    if [ "$arch" = "i686" ]; then
+        arch="i386"
+    elif [ "$arch" = "x86_64" ]; then
+        arch="amd64"
+    elif [ "$arch" = "armv7l" ]; then
+        arch="armhf"
+    fi
+fi
+hostarch=$arch
 
 while true
 do
     case "$1" in
-        -h|--help)      usage $0 && exit 0;;
+        -h|--help)      usage $0 && exit 1;;
         -p|--path)      path=$2; shift 2;;
-	-n|--name)      name=$2; shift 2;;
+        --rootfs)       rootfs=$2; shift 2;;
+        -a|--arch)      arch=$2; shift 2;;
+        -r|--release)   release=$2; shift 2;;
+        -n|--name)      name=$2; shift 2;;
+        -c|--clean)     clean=$2; shift 1;;
         --)             shift 1; break ;;
         *)              break ;;
     esac
 done
+
+if [ ! -z "$clean" -a -z "$path" ]; then
+    clean || exit 1
+    exit 0
+fi
+
+if [ "$arch" = "i686" ]; then
+    arch=i386
+fi
+
+if [ "$arch" = "x86_64" ]; then
+    arch=amd64
+fi
+
+if [ $hostarch = "i386" -a $arch = "amd64" ]; then
+    echo "can't create $arch container on $hostarch"
+    exit 1
+fi
+
+if [ $hostarch = "armhf" -o $hostarch = "armel" ] && \
+   [ $arch != "armhf" -a $arch != "armel" ]; then
+    echo "can't create $arch container on $hostarch"
+    exit 1
+fi
+
+if [ $hostarch = "powerpc" -a $arch != "powerpc" ]; then
+    echo "can't create $arch container on $hostarch"
+    exit 1
+fi
+
+type debootstrap
+if [ $? -ne 0 ]; then
+    echo "'debootstrap' command is missing"
+    exit 1
+fi
 
 if [ -z "$path" ]; then
     echo "'path' parameter is required"
@@ -292,9 +434,28 @@ if [ "$(id -u)" != "0" ]; then
     exit 1
 fi
 
-rootfs=$path/rootfs
+current_release=`wget ${MIRROR}/dists/stable/Release -O - 2>/dev/null |\
+head |awk '/^Codename: (.*)$/ { print $2; }'`
+release=${release:-${current_release}}
+valid_releases=('squeeze' 'wheezy' 'jessie' 'sid')
+if [[ ! "${valid_releases[*]}" =~ (^|[^[:alpha:]])$release([^[:alpha:]]|$) ]]
+then
+    echo "Invalid release ${release}, valid ones are: ${valid_releases[*]}"
+    exit 1
+fi
 
-install_debian $rootfs
+# detect rootfs
+config="$path/config"
+if [ -z "$rootfs" ]; then
+    if grep -q '^lxc.rootfs' $config 2>/dev/null ; then
+        rootfs=$(awk -F= '/^lxc.rootfs =/{ print $2 }' $config)
+    else
+        rootfs=$path/rootfs
+    fi
+fi
+
+
+install_debian $rootfs $release $arch
 if [ $? -ne 0 ]; then
     echo "failed to install debian"
     exit 1
@@ -306,7 +467,13 @@ if [ $? -ne 0 ]; then
     exit 1
 fi
 
-copy_configuration $path $rootfs $name
+bootstrap_ginas $rootfs $name
+if [ $? -ne 0 ]; then
+    echo "failed to bootstrap ginas a container"
+    exit 1
+fi
+
+copy_configuration $path $rootfs $name $arch
 if [ $? -ne 0 ]; then
     echo "failed write configuration file"
     exit 1
@@ -316,5 +483,3 @@ if [ ! -z $clean ]; then
     clean || exit 1
     exit 0
 fi
-
-
