Log everything to 1 file and refactor the worker service

diff --git a/playbooks/roles/ginas.rails_deploy/templates/etc/init.d/service.j2 b/playbooks/roles/ginas.rails_deploy/templates/etc/init.d/service.j2
--- a/playbooks/roles/ginas.rails_deploy/templates/etc/init.d/service.j2
+++ b/playbooks/roles/ginas.rails_deploy/templates/etc/init.d/service.j2
@@ -1,17 +1,21 @@
 #! /bin/bash
-
+{% set rails_deploy_tpl_label = rails_deploy_service if item == 'service' else rails_deploy_worker -%}
+{% set rails_deploy_tpl_bin = rails_deploy_backend if item == 'service' else rails_deploy_worker -%}
+{% set rails_deploy_tpl_pid = rails_deploy_service_pid if item == 'service' else rails_deploy_worker_pid -%}
+{% set rails_deploy_tpl_config = rails_deploy_backend + '.rb' if item == 'service' else rails_deploy_worker + '.yml' -%}
+{% set rails_deploy_tpl_respond_to = 'start|stop|restart|reload|status' if item == 'service' else 'start|stop|restart|status}' -%}
 # {{ ansible_managed }}
 
 # Heavily inspired by: https://github.com/gitlabhq/gitlabhq
 
 ### BEGIN INIT INFO
-# Provides:          {{ rails_deploy_service }}
-# Required-Start:    $local_fs $remote_fs $network
-# Required-Stop:     $local_fs $remote_fs $network
+# Provides:          {{ rails_deploy_tpl_label }}
+# Required-Start:    $local_fs $remote_fs $network $rsyslog
+# Required-Stop:     $local_fs $remote_fs $network $rsyslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: Manage a rails web server process
-# Description:       Manage a rails web server process
+# Short-Description: Manage {{ rails_deploy_tpl_label }}
+# Description:       Manage {{ rails_deploy_tpl_label }}
 ### END INIT INFO
 
 # ---------------------------------------------------------------------------
@@ -19,81 +23,91 @@
 # ---------------------------------------------------------------------------
 bundle="bundle"
 
-app_service="{{ rails_deploy_service }}"
-app_user="{{ rails_deploy_service }}"
-app_home="{{ rails_deploy_home }}"
-app_src="{{ rails_deploy_src }}"
-app_env_source="{{ rails_deploy_env_source }}"
-app_run="{{ rails_deploy_run }}"
-app_socket="{{ rails_deploy_service_socket }}"
-app_pid="{{ rails_deploy_service_pid }}"
-app_backend="{{ rails_deploy_backend }}"
-app_bin="{{ rails_deploy_src }}/bin/{{ rails_deploy_backend }}"
+service="{{ rails_deploy_tpl_label }}"
+user="{{ rails_deploy_service }}"
+home="{{ rails_deploy_home }}"
+src="{{ rails_deploy_src }}"
+env_source="{{ rails_deploy_env_source }}"
+run="{{ rails_deploy_run }}"
+bin="{{ rails_deploy_src }}/bin/{{ rails_deploy_tpl_bin }}"
 
-{% if rails_deploy_backend == 'puma' -%}
-backend_config="C"
-backend_daemon="d"
-{% elif rails_deploy_backend == 'unicorn' -%}
-backend_config="c"
-backend_daemon="D"
+{% if item == 'service' %}
+socket="{{ rails_deploy_service_socket }}"
+{% endif %}
+pid="{{ rails_deploy_tpl_pid }}"
+
+{% if rails_deploy_tpl_bin == 'puma' or rails_deploy_tpl_bin == 'sidekiq' -%}
+config="C"
+daemon="d"
+{% elif rails_deploy_tpl_bin == 'unicorn' -%}
+config="c"
+daemon="D"
 {% endif -%}
-backend_reload="USR2"
-backend_stop="KILL"
 
-backend_config_flag="-$backend_config $app_src/config/{{ rails_deploy_backend }}.rb"
+config_flag="-$config $src/config/{{ rails_deploy_tpl_config }}"
 
 # ---------------------------------------------------------------------------
-# source the environment, ensure correct user, switch into the app's path
+# source the environment, ensure correct user, and set the path
 # ---------------------------------------------------------------------------
-if ! $app_env_source ; then
- echo "failed to source environment for $app_service, exiting"; exit 1;
+if ! $env_source ; then
+ echo "failed to source environment for $service, exiting"; exit 1;
 fi
 
-if [ "$USER" != "$app_user" ]; then
-  eval su - "$app_user" -c $(echo \")$0 "$@"$(echo \"); exit;
+if [ "$USER" != "$user" ]; then
+  eval su - "$user" -c $(echo \")$0 "$@"$(echo \"); exit;
 fi
 
-if ! cd "$app_src" ; then
- echo "failed to cd into $app_src, exiting"; exit 1;
+if ! cd "$src" ; then
+ echo "failed to cd into $src, exiting"; exit 1;
 fi
 
 # ---------------------------------------------------------------------------
-# private commands related to {{ rails_deploy_service }}
+# private commands to control {{ rails_deploy_tpl_label }}
 # ---------------------------------------------------------------------------
-server_start(){
-  $bundle exec $app_bin $backend_config_flag -$backend_daemon
+{% if item == 'service' %}
+service_start(){
+$bundle exec $bin $config_flag -$daemon 2>&1 | logger -t {{ rails_deploy_backend }} &
 }
 
-server_stop(){
-  kill -$backend_stop $wpid
+service_stop(){
+  kill -KILL $wpid
 }
 
-server_reload(){
-  kill -$backend_reload $wpid
+service_reload(){
+  kill -USR2 $wpid
 }
+{% else %}
+service_start(){
+$bundle exec $bin $config_flag -$daemon 2>&1 | logger -t {{ rails_deploy_worker }} &
+}
+
+service_stop(){
+  $bundle exec bin/sidekiqctl stop $pid
+}
+{% endif %}
 
 # ---------------------------------------------------------------------------
 # get the pid from the file
 # ---------------------------------------------------------------------------
 check_pids(){
-  if ! mkdir -p "$app_run"; then
-    echo "could not create the path $app_run needed to store the pids"; exit 1
+  if ! mkdir -p "$run"; then
+    echo "could not create the path $run needed to store the pids"; exit 1
   fi
-  if [ -f "$app_pid" ]; then
+  if [ -f "$pid" ]; then
     # read an existing pid file
-    wpid=$(cat "$app_pid")
+    wpid=$(cat "$pid")
   else
     wpid=0
   fi
 }
 
 # ---------------------------------------------------------------------------
-# used after starting the app service and are waiting for its pid
+# used after starting the service and are waiting for its pid
 # ---------------------------------------------------------------------------
 wait_for_pids(){
   # sleep for a bit to give it time
   i=0;
-  while [ ! -f $app_pid ]; do
+  while [ ! -f $pid ]; do
     sleep 0.1;
     i=$((i+1))
     if [ $((i%10)) = 0 ]; then
@@ -112,20 +126,20 @@ wait_for_pids(){
 check_pids
 
 # ---------------------------------------------------------------------------
-# determine if the app process is running or not
+# determine if the service is running or not
 # ---------------------------------------------------------------------------
 check_status(){
   check_pids
 
-  # if the web server is running kill -0 $server_pid returns true, or rather 0
+  # if the service is running kill -0 $pid returns true, or rather 0
   # checks of *_status should only check for == 0 or != 0, never anything else
   if [ $wpid -ne "0" ]; then
     kill -0 "$wpid" 2>/dev/null
-    server_status="$?"
+    service_status="$?"
   else
-    server_status="-1"
+    service_status="-1"
   fi
-  if [ $server_status = 0 ]; then
+  if [ $service_status = 0 ]; then
     exit_status=0
   else
     # http://refspecs.linuxbase.org/LSB_4.1.0/LSB-Core-generic/LSB-Core-generic/iniscrptact.html
@@ -141,9 +155,9 @@ check_stale_pids(){
   check_status
   # if there is a pid it is something else than 0, the service is running if
   # *_status is == 0
-  if [ "$wpid" != "0" -a "$server_status" != "0" ]; then
-    echo "removing stale $app_service pid, this is most likely caused by $app_name crashing the last time it ran"
-    if ! rm "$app_pid"; then
+  if [ "$wpid" != "0" -a "$service_status" != "0" ]; then
+    echo "removing stale $service pid, this is most likely caused by $service crashing the last time it ran"
+    if ! rm "$pid"; then
       echo "unable to remove stale pid, exiting"
       exit 1
     fi
@@ -155,57 +169,60 @@ check_stale_pids(){
 # ---------------------------------------------------------------------------
 exit_if_not_running(){
   check_stale_pids
-  if [ "$server_status" != "0" ]; then
-    echo "$app_service is not running"
+  if [ "$service_status" != "0" ]; then
+    echo "$service is not running"
     exit
   fi
 }
 
 # ---------------------------------------------------------------------------
-# start the app process if it is not running
+# start the service if it is not running
 # ---------------------------------------------------------------------------
-start_app() {
+start() {
   check_stale_pids
 
-  if [ "$server_status" != "0" ]; then
-    echo -n "starting $app_service"
+  if [ "$service_status" != "0" ]; then
+    echo -n "starting $service"
   fi
 
   # then check if the service is running
   # if it is, don't start again
-  if [ "$server_status" = "0" ]; then
-    echo "$app_service is already running with pid $wpid, not restarting"
+  if [ "$service_status" = "0" ]; then
+    echo "$service is already running with pid $wpid, not restarting"
   else
+{% if item == 'service' %}
     # remove old socket if it exists before starting
-    rm -f "$app_socket" 2>/dev/null
-    server_start
+    rm -f "$socket" 2>/dev/null
+{% endif %}
+    service_start
   fi
 
   # wait for the pids to be planted
   wait_for_pids
 
-  # finally check the status to tell wether or not the app process is running
+  # finally check the status to tell whether or not the service is running
   print_status
 }
 
 # ---------------------------------------------------------------------------
-# stop the app process if it is running
+# stop the service if it is running
 # ---------------------------------------------------------------------------
-stop_app() {
+stop() {
   exit_if_not_running
 
-  # if the app process is running, stop it
-  if [ "$server_status" = "0" ]; then
-    echo -n "shutting down $app_service"
-    server_stop
+  # if the service is running, stop it
+  if [ "$service_status" = "0" ]; then
+    echo -n "shutting down $service"
+    service_stop
   fi
 
-  # if something needs to be stopped, wait for it because using SIGKILL is bad in a script
-  while [ "$server_status" = "0" ]; do
+  # if something needs to be stopped, wait for it because
+  # using SIGKILL is bad in a script
+  while [ "$service_status" = "0" ]; do
     sleep 1
     check_status
     printf "."
-    if [ "$server_status" != "0" ]; then
+    if [ "$service_status" != "0" ]; then
       printf "\n"
       break
     fi
@@ -214,56 +231,56 @@ stop_app() {
   sleep 1
 
   # clean up the pid file
-  rm "$app_pid" 2>/dev/null
+  rm "$pid" 2>/dev/null
 
   print_status
 }
 
 # ---------------------------------------------------------------------------
-# output the status of this app process
+# output the status of the service
 # ---------------------------------------------------------------------------
 print_status() {
   check_status
-  if [ "$server_status" != "0" ]; then
-    echo "$app_service is not running"
+  if [ "$service_status" != "0" ]; then
+    echo "$service is not running"
     return
   fi
-  if [ "$server_status" = "0" ]; then
-      echo "$app_service with pid $wpid is running"
+  if [ "$service_status" = "0" ]; then
+      echo "$service with pid $wpid is running"
   else
-      printf "$app_service is \033[31mnot running\033[0m\n"
+      printf "$service is \033[31mnot running\033[0m\n"
   fi
-  if [ "$server_status" = "0" ]; then
-    printf "$app_service is \033[32mup and running\033[0m\n"
+  if [ "$service_status" = "0" ]; then
+    printf "$service is \033[32mup and running\033[0m\n"
   fi
 }
-
+{% if item == 'service' %}
 # ---------------------------------------------------------------------------
 # reload the app process
 # ---------------------------------------------------------------------------
-reload_app(){
+reload(){
   exit_if_not_running
   if [ "$wpid" = "0" ];then
-    echo "$app_service is not running, its configuration can't be reloaded, exiting"
+    echo "$service is not running, its configuration can't be reloaded, exiting"
     exit 1
   fi
-  printf "reloading $app_service configuration..."
-  server_reload
+  printf "reloading $service configuration..."
+  service_reload
   echo "done!"
 
   wait_for_pids
   print_status
 }
-
+{% endif %}
 # ---------------------------------------------------------------------------
 # restart the app process by stopping it and then starting it
 # ---------------------------------------------------------------------------
-restart_app(){
+restart(){
   check_status
-  if [ "$server_status" = "0" ]; then
-    stop_app
+  if [ "$service_status" = "0" ]; then
+    stop
   fi
-  start_app
+  start
 }
 
 # ---------------------------------------------------------------------------
@@ -271,23 +288,25 @@ restart_app(){
 # ---------------------------------------------------------------------------
 case "$1" in
   start)
-        start_app
+        start
         ;;
   stop)
-        stop_app
+        stop
         ;;
   restart)
-        restart_app
+        restart
         ;;
+{% if item == 'service' %}
   reload|force-reload)
-        reload_app
+        reload
         ;;
+{% endif %}
   status)
         print_status
         exit $exit_status
         ;;
   *)
-        echo "Usage: service $app_service {start|stop|restart|reload|status}"
+        echo "Usage: service $service { {{ rails_deploy_tpl_respond_to }} }"
         exit 1
         ;;
 esac
