Added error message to 'clean' git-shell-command

diff --git a/playbooks/roles/users/templates/srv/users/git-shell-commands/clean.j2 b/playbooks/roles/users/templates/srv/users/git-shell-commands/clean.j2
--- a/playbooks/roles/users/templates/srv/users/git-shell-commands/clean.j2
+++ b/playbooks/roles/users/templates/srv/users/git-shell-commands/clean.j2
@@ -32,6 +32,8 @@ if [ -d ${worktree} ] ; then
 	rm -rf ${worktree}
 	mkdir -p ${worktree}
 	echo "Work tree of ${repository} cleaned"
+else
+	echo "Error: Work tree ${worktree} not found" && exit 1
 fi
 
 
