Added more descriptive messages in git-shell

diff --git a/playbooks/roles/users/templates/srv/users/git-shell-commands/deploy.j2 b/playbooks/roles/users/templates/srv/users/git-shell-commands/deploy.j2
--- a/playbooks/roles/users/templates/srv/users/git-shell-commands/deploy.j2
+++ b/playbooks/roles/users/templates/srv/users/git-shell-commands/deploy.j2
@@ -41,7 +41,17 @@ if [ -d ${project} ] ; then
 			echo "Error: Branch ${branch} not found" && exit 1
 		fi
 	fi
-	[ -x ./hooks/post-receive ] && ./hooks/post-receive
+
+	if [ -z "${currentworktree}" ] ; then
+		echo "Error: No work tree specified" && exit 1
+	fi
+
+	if [ -x ./hooks/post-receive ] ; then
+		./hooks/post-receive
+		echo "Deployed ${repository}:${branch:-${currentbranch}} to ${currentworktree}"
+	else
+		echo "Error: Deploy script in ${repository} missing, cannot deploy" && exit 1
+	fi
 else
 	echo "Error: No repository named ${repository}" && exit 1
 fi
diff --git a/playbooks/roles/users/templates/srv/users/git-shell-commands/rename.j2 b/playbooks/roles/users/templates/srv/users/git-shell-commands/rename.j2
--- a/playbooks/roles/users/templates/srv/users/git-shell-commands/rename.j2
+++ b/playbooks/roles/users/templates/srv/users/git-shell-commands/rename.j2
@@ -36,7 +36,13 @@ if [ -d ${project} ] ; then
 	if [[ ${newrepository} == */* ]] ; then
 		mkdir -p $(dirname ${HOME}/${newrepository})
 	fi
-	mv "${HOME}/${project}" "${HOME}/${newproject}"
+	if [ -d ${newproject} ] ; then
+		echo "Error: Repository ${newrepository} already exists" && exit 1
+	else
+		mv "${HOME}/${project}" "${HOME}/${newproject}"
+		echo "Repository ${repository} renamed to ${newrepository}"
+		exit 0
+	fi
 else
 	echo "Error: Repository ${repository} not found" && exit 1
 fi
